"""Generate Stage-1 (Trajectory) training configs.

Single variant this round: ``stage1_traj_v0``. From scratch, full data,
seed 42, bs=64 / accum=1 / 80 ep. Architecture per
``analyses/2026-05-29_stage1_and_stage1_5_design.md`` §"Stage-1 design".

Outputs:
    configs/training/stage1_traj_v0.yaml
    analyses/round31_stage1_manifest.json
    analyses/round31_stage1_manifest.md

Usage:
    python scripts/stage_a_generator/round31_make_stage1_configs.py
    python scripts/stage_a_generator/round31_make_stage1_configs.py --dry-run
    python scripts/stage_a_generator/round31_make_stage1_configs.py \\
        --data-root /media/8TB_data/Cai/datasets/InterAct/piano_official_process_4
"""
from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG_DIR = ROOT / "configs" / "training"
DEFAULT_ANALYSES_DIR = ROOT / "analyses"
DEFAULT_DATA_ROOT = "E:/Project/Datasets/InterAct/piano_official_process_4"
DATASET_SUBSET_NAMES: tuple[str, ...] = (
    "chairs", "imhd", "neuraldome", "omomo_correct_v2",
)

SCHEDULE_BATCH_SIZE = 64
SCHEDULE_ACCUM_STEPS = 1
SCHEDULE_NUM_EPOCHS = 80

ARCH_D_MODEL = 256
ARCH_N_LAYERS = 4
ARCH_N_HEADS = 4
ARCH_FF_MULT = 4
ARCH_DROPOUT = 0.1


@dataclass(slots=True)
class Stage1Variant:
    variant_id: str
    purpose: str

    # Architecture.
    d_model: int = ARCH_D_MODEL
    n_layers: int = ARCH_N_LAYERS
    n_heads: int = ARCH_N_HEADS
    ff_mult: int = ARCH_FF_MULT
    dropout: float = ARCH_DROPOUT
    use_text: bool = True

    # Loss weights.
    w_x0: float = 1.0
    w_vel: float = 1.0
    # yaw_smooth on z-scored sin/cos channels is dubious (atan2 of
    # normalised values does not return a valid angle). Keep at 0 by
    # default; flip on only after verifying behaviour on a 48-clip overfit.
    w_yaw_smooth: float = 0.0
    use_min_snr_weighting: bool = True
    min_snr_gamma: float = 5.0

    val_best_key: str = "mse_x0"


VARIANTS: list[Stage1Variant] = [
    Stage1Variant(
        variant_id="stage1_traj_v0",
        purpose=(
            "Stage-1 v0: 23-D stage1_coarse generator. DiT-Zero + PixArt "
            "cross-attn family, d_model=256 n_layers=4 (≈3 M params). "
            "From scratch, full data, 80 ep, seed 42, bs=64."
        ),
    ),
]


def _render_datasets_block(data_root: str) -> str:
    stripped = data_root.rstrip("/").rstrip("\\")
    lines: list[str] = []
    for sub in DATASET_SUBSET_NAMES:
        lines.append(f'    - name: "{sub}"')
        lines.append(f'      root: "{stripped}/{sub}"')
    return "\n".join(lines)


def _render_yaml(v: Stage1Variant, *, data_root: str) -> str:
    run_name = v.variant_id     # variant_id already starts with "stage1_"
    use_text = "true" if v.use_text else "false"
    use_min_snr = "true" if v.use_min_snr_weighting else "false"
    return f"""# Stage-1 (Trajectory) training config — {v.variant_id}
#
# Generated by scripts/stage_a_generator/round31_make_stage1_configs.py.
# Per analyses/2026-05-29_stage1_and_stage1_5_design.md §"Stage-1 design".
#
# Output: 23-D stage1_coarse (Stage-2 PB1 cond contract).
# FULL DATA. No subset_indices_file. From scratch (no init_checkpoint).
# Heldout val. {SCHEDULE_NUM_EPOCHS} ep / val_every=5 / save_every=10 / warmup=500.
# Schedule: bs={SCHEDULE_BATCH_SIZE} accum={SCHEDULE_ACCUM_STEPS} (2× 5080).

model:
  cfg_drop_prob: 0.15
  diffusion:
    num_steps: 1000
    schedule: "cosine"
    prediction_target: "x0"
  denoiser:
    motion_dim: 23                  # stage1_coarse_dim — fixed by Stage-2 input contract
    object_traj_dim: 9
    text_dim: 512
    object_token_dim: 256
    object_num_tokens: 128
    d_model: {v.d_model}
    n_layers: {v.n_layers}
    n_heads: {v.n_heads}
    ff_mult: {v.ff_mult}
    dropout: {v.dropout}
    use_text: {use_text}
  object_encoder:
    num_input_points: 1024
    num_output_tokens: 128
    feature_dim: 256
  text_encoder:
    clip_version: "ViT-B/32"
    download_root: "cache/clip"

data:
  datasets:
{_render_datasets_block(data_root)}
  pseudo_label_dir: null
  pseudo_label_subdir: "pseudo_labels/v18_h10_f05_pelvis20_official_semantic_marker"
  max_seq_length: 196
  support_collapse_hand_support: true
  motion_representation: "smpl_pose_135_plan"
  force_world_frame: true
  subsample_n_per_object: null
  overfit_n_clips: 0
  stage1_coarse_cache_root: "cache/stage1_coarse_v1_full"
  surface_temporal_aux_fields: false
  # No R29 typed conds — Stage-1 doesn't consume them.
  r29_coarse_variant: "C23"
  r29_interaction_variant: "I0"
  r29_support_variant: "S0"
  r29_body_variant: "B0"
  r29_body_coord_frame: null
  r29_body_energy_threshold: 0.05
  r29_body_lowpass_window: 9
  r29_hand_offset_clamp_m: 2.0
  subject_split:
    enabled: true
    train_pct: 85
    val_pct: 15
    seed: 42
  augmentation:
    enabled: false
    mirror_prob: 0.0
    rotate_around_y_prob: 0.0
    pc_jitter_std: 0.0

training:
  batch_size: {SCHEDULE_BATCH_SIZE}
  num_epochs: {SCHEDULE_NUM_EPOCHS}
  num_workers: 4
  seed: 42
  optimizer:
    name: "adamw"
    lr: 1.0e-4
    weight_decay: 0.01
    betas: [0.9, 0.999]
  scheduler:
    name: "cosine"
    warmup_steps: 500
  gradient_accumulation_steps: {SCHEDULE_ACCUM_STEPS}
  max_grad_norm: 1.0
  mixed_precision: "bf16"
  val_every_epochs: 5
  val_best_key: "{v.val_best_key}"

loss:
  w_x0: {v.w_x0}
  w_vel: {v.w_vel}
  w_yaw_smooth: {v.w_yaw_smooth}
  use_min_snr_weighting: {use_min_snr}
  min_snr_gamma: {v.min_snr_gamma}

logging:
  project: "piano"
  run_name: "{run_name}"
  log_every_n_steps: 50
  save_every_n_epochs: 10

output_dir: "runs/training/{run_name}"
"""


def _manifest_row(v: Stage1Variant) -> dict:
    return {
        "variant_id": v.variant_id,
        "group": "Stage1Trajectory",
        "purpose": v.purpose,
        "train": True,
        "from_scratch": True,
        "architecture": {
            "d_model": v.d_model, "n_layers": v.n_layers,
            "n_heads": v.n_heads, "ff_mult": v.ff_mult,
            "dropout": v.dropout, "use_text": v.use_text,
        },
        "schedule": {
            "batch_size": SCHEDULE_BATCH_SIZE,
            "gradient_accumulation_steps": SCHEDULE_ACCUM_STEPS,
            "num_epochs": SCHEDULE_NUM_EPOCHS,
            "lr": 1.0e-4, "warmup_steps": 500,
            "mixed_precision": "bf16", "seed": 42,
            "val_every_epochs": 5, "save_every_n_epochs": 10,
            "val_best_key": v.val_best_key,
        },
        "loss": {
            "w_x0": v.w_x0, "w_vel": v.w_vel,
            "w_yaw_smooth": v.w_yaw_smooth,
            "use_min_snr_weighting": v.use_min_snr_weighting,
            "min_snr_gamma": v.min_snr_gamma,
        },
        "config_path": f"configs/training/{v.variant_id}.yaml",
        "output_dir": f"runs/training/{v.variant_id}",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--data-root",
        default=os.environ.get("DATASETS_ROOT", DEFAULT_DATA_ROOT),
    )
    parser.add_argument("--config-dir", default=str(DEFAULT_CONFIG_DIR))
    parser.add_argument("--analyses-dir", default=str(DEFAULT_ANALYSES_DIR))
    args = parser.parse_args()

    config_dir = Path(args.config_dir)
    analyses_dir = Path(args.analyses_dir)

    rows: list[dict] = []
    for v in VARIANTS:
        out_path = config_dir / f"{v.variant_id}.yaml"
        content = _render_yaml(v, data_root=args.data_root)
        rows.append(_manifest_row(v))
        if args.dry_run:
            print(f"DRY-RUN would write: {out_path}  ({len(content)} bytes)")
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            print(f"wrote {out_path}")

    manifest_json = analyses_dir / "round31_stage1_manifest.json"
    manifest_md = analyses_dir / "round31_stage1_manifest.md"
    md_lines: list[str] = [
        "# Round-31 Stage-1 (Trajectory) manifest",
        "",
        "Per `analyses/2026-05-29_stage1_and_stage1_5_design.md`. FULL "
        f"InterAct train set, from scratch, seed 42, {SCHEDULE_NUM_EPOCHS} ep, "
        f"bs={SCHEDULE_BATCH_SIZE} / accum={SCHEDULE_ACCUM_STEPS} (2× 5080).",
        "",
        "## Variants",
        "",
        "| variant | arch | loss weights |",
        "|---|---|---|",
    ]
    for v in VARIANTS:
        md_lines.append(
            f"| `{v.variant_id}` | d_model={v.d_model} L={v.n_layers} | "
            f"w_x0={v.w_x0} w_vel={v.w_vel} w_yaw_sm={v.w_yaw_smooth} |"
        )
    md_lines.append("")

    if args.dry_run:
        print(f"DRY-RUN would write: {manifest_json}")
        print(f"DRY-RUN would write: {manifest_md}")
    else:
        analyses_dir.mkdir(parents=True, exist_ok=True)
        manifest_json.write_text(
            json.dumps(
                {"variants": rows, "data_root": args.data_root},
                indent=2,
            ) + "\n", encoding="utf-8",
        )
        manifest_md.write_text("\n".join(md_lines), encoding="utf-8")
        print(f"wrote {manifest_json}")
        print(f"wrote {manifest_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
