"""Motion visualization tool: render skeleton animations as MP4.

Supports two input sources:
    1. Real preprocessed dataset samples (from HOIDataset output)
    2. Generated motion from a smoke-test / inference run (.npz file)

Usage examples:

    # Visualize 4 real sequences from the preprocessed dataset
    python -m piano.inference.visualize_motion real \\
        --data-dir /media/.../datasets/omomo/piano \\
        --seq-ids sub10_clothesstand_000 sub11_largebox_003 sub12_monitor_001 \\
        --output-dir runs/visualizations/2026-04-19_real_samples

    # Visualize motion generated by the smoke test
    python -m piano.inference.visualize_motion generated \\
        --run-dir runs/checks/inference_smoke_test/2026-04-19_063940 \\
        --output-dir runs/visualizations/2026-04-19_smoke_generated
"""
from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import numpy as np

from piano.utils.io_utils import ensure_dir, load_json, save_json


# ---------------------------------------------------------------------------
# SMPL 22-joint skeleton for rendering
# ---------------------------------------------------------------------------

SKELETON_CONNECTIONS: list[tuple[int, int]] = [
    (0, 1), (0, 2), (0, 3),        # pelvis → left_hip, right_hip, spine1
    (1, 4), (2, 5), (3, 6),        # hips → knees, spine1 → spine2
    (4, 7), (5, 8), (6, 9),        # knees → ankles, spine2 → spine3
    (7, 10), (8, 11),              # ankles → feet
    (9, 12), (9, 13), (9, 14),     # spine3 → neck, collars
    (12, 15),                      # neck → head
    (13, 16), (14, 17),            # collars → shoulders
    (16, 18), (17, 19),            # shoulders → elbows
    (18, 20), (19, 21),            # elbows → wrists
]


# ---------------------------------------------------------------------------
# Motion decoding
# ---------------------------------------------------------------------------

def motion_263_to_joints(
    motion: np.ndarray,
    fps: float = 20.0,
) -> np.ndarray:
    """Reconstruct approximate absolute joint positions from HumanML3D features.

    The 263-dim representation encodes:
        [0]     root angular velocity (rad/s)
        [1:3]   root xz linear velocity (m/s)
        [3]     root height (m)
        [4:67]  relative joint positions w.r.t. root (21 joints × 3)
        [67:133] joint velocities (22 × 3)
        [133:259] 6D joint rotations (21 × 6)
        [259:263] foot contact labels

    We integrate the root xz velocity to recover root trajectory, then
    add relative joint positions to produce (T, 22, 3) absolute positions.

    Parameters
    ----------
    motion : (T, 263) — HumanML3D features (in the same unit as training)
    fps : frame rate (used to convert root velocity m/s → per-frame delta)
    """
    T = len(motion)
    dt = 1.0 / fps

    root_vel_xz = motion[:, 1:3]          # (T, 2) — m/s
    root_height = motion[:, 3]            # (T,)   — m
    rel_positions = motion[:, 4:67].reshape(T, 21, 3)  # (T, 21, 3) relative to root

    # Integrate root xz trajectory
    root_pos = np.zeros((T, 3), dtype=np.float32)
    root_pos[:, 1] = root_height
    for t in range(1, T):
        root_pos[t, 0] = root_pos[t - 1, 0] + root_vel_xz[t, 0] * dt
        root_pos[t, 2] = root_pos[t - 1, 2] + root_vel_xz[t, 1] * dt

    joints = np.zeros((T, 22, 3), dtype=np.float32)
    joints[:, 0, :] = root_pos
    joints[:, 1:, :] = rel_positions + root_pos[:, None, :]
    return joints


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def render_motion_video(
    joints: np.ndarray,
    output_path: Path,
    fps: float = 20.0,
    title: str = "",
    object_positions: np.ndarray | None = None,
    object_pc: np.ndarray | None = None,
    elev: float = 15.0,
    azim: float = -60.0,
    dpi: int = 80,
) -> None:
    """Render a skeleton animation (optionally with object) to MP4 or GIF.

    Parameters
    ----------
    joints : (T, 22, 3) — absolute joint positions
    output_path : where to save (.mp4 or .gif)
    fps : playback frame rate
    title : shown on the plot
    object_positions : (T, 3) — optional per-frame object center to overlay
    object_pc : (N, 3) — optional object point cloud in object-local frame;
        rendered at the object_positions location each frame.
    elev, azim : initial camera angles
    dpi : output resolution
    """
    import matplotlib.pyplot as plt
    from matplotlib.animation import FuncAnimation
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

    T = len(joints)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Compute axis limits covering all frames
    all_pos = [joints.reshape(-1, 3)]
    if object_positions is not None:
        all_pos.append(object_positions)
    all_pos = np.concatenate(all_pos, axis=0)
    center = all_pos.mean(axis=0)
    max_range = max((all_pos.max(axis=0) - all_pos.min(axis=0)).max() / 2 * 1.2, 0.5)

    fig = plt.figure(figsize=(7, 7))
    ax = fig.add_subplot(111, projection="3d")

    joint_scatter = ax.scatter([], [], [], c="blue", s=20)
    lines = [ax.plot([], [], [], c="gray", linewidth=1.5)[0] for _ in SKELETON_CONNECTIONS]
    object_scatter = None
    if object_positions is not None or object_pc is not None:
        object_scatter = ax.scatter([], [], [], c="red", s=30, marker="^")

    ax.set_xlim(center[0] - max_range, center[0] + max_range)
    ax.set_ylim(center[2] - max_range, center[2] + max_range)
    ax.set_zlim(center[1] - max_range, center[1] + max_range)
    ax.set_xlabel("X")
    ax.set_ylabel("Z")
    ax.set_zlabel("Y")
    ax.view_init(elev=elev, azim=azim)
    title_artist = ax.set_title("")

    def update(t: int) -> list:
        artists: list = []
        # Plot body joints (swap axes so Y-up works in matplotlib 3D)
        joint_scatter._offsets3d = (
            joints[t, :, 0],
            joints[t, :, 2],
            joints[t, :, 1],
        )
        artists.append(joint_scatter)
        for (i, j), line in zip(SKELETON_CONNECTIONS, lines):
            line.set_data(
                [joints[t, i, 0], joints[t, j, 0]],
                [joints[t, i, 2], joints[t, j, 2]],
            )
            line.set_3d_properties([joints[t, i, 1], joints[t, j, 1]])
            artists.append(line)
        # Object marker (single point at COM, or full point cloud)
        if object_scatter is not None:
            if object_pc is not None and object_positions is not None:
                # Object pc in object-local frame, offset to world position
                pos = object_pc + object_positions[t][None, :]
                object_scatter._offsets3d = (pos[:, 0], pos[:, 2], pos[:, 1])
            elif object_positions is not None:
                p = object_positions[t]
                object_scatter._offsets3d = ([p[0]], [p[2]], [p[1]])
            artists.append(object_scatter)

        title_artist.set_text(f"{title}\nFrame {t+1}/{T} ({t/fps:.2f}s)")
        artists.append(title_artist)
        return artists

    anim = FuncAnimation(
        fig, update, frames=T, interval=1000 / fps, blit=False, repeat=False,
    )

    # Save: try ffmpeg first for mp4, fall back to pillow for gif
    suffix = output_path.suffix.lower()
    try:
        if suffix == ".mp4":
            anim.save(str(output_path), writer="ffmpeg", fps=fps, dpi=dpi)
        else:
            anim.save(str(output_path), writer="pillow", fps=fps, dpi=dpi)
    except Exception as e:
        # ffmpeg unavailable — fall back to gif
        gif_path = output_path.with_suffix(".gif")
        print(f"  [warn] {e}; falling back to {gif_path}")
        anim.save(str(gif_path), writer="pillow", fps=fps, dpi=dpi)
        output_path = gif_path
    finally:
        plt.close(fig)

    print(f"  Saved: {output_path}")


# ---------------------------------------------------------------------------
# Input source adapters
# ---------------------------------------------------------------------------

def load_real_samples(
    data_dir: Path, seq_ids: list[str] | None, num_samples: int,
) -> list[dict]:
    """Load preprocessed motion sequences from the PIANO-format dataset."""
    metadata = load_json(data_dir / "metadata.json")
    if seq_ids:
        wanted = set(seq_ids)
        selected = [m for m in metadata if m["seq_id"] in wanted]
        if len(selected) != len(seq_ids):
            missing = wanted - {m["seq_id"] for m in selected}
            print(f"  [warn] missing seq_ids: {missing}")
    else:
        selected = metadata[:num_samples]

    samples: list[dict] = []
    for meta in selected:
        npz_path = data_dir / "motions" / f"{meta['seq_id']}.npz"
        if not npz_path.exists():
            print(f"  [warn] {npz_path} not found, skipping")
            continue
        data = np.load(npz_path)
        samples.append({
            "seq_id": meta["seq_id"],
            "text": meta.get("text", ""),
            "motion_263": data["motion_263"],
            "joints_22": data["joints_22"],        # absolute joints from preprocessing
            "object_positions": data.get("object_positions") if "object_positions" in data.files else None,
            "num_frames": int(data["motion_263"].shape[0]),
        })
    return samples


def load_generated_samples(run_dir: Path) -> list[dict]:
    """Load generated motions from a smoke-test run directory."""
    npz_path = run_dir / "generated.npz"
    summary_path = run_dir / "summary.json"
    if not npz_path.exists():
        raise FileNotFoundError(f"No generated.npz in {run_dir}")
    data = np.load(npz_path)
    motion = data["motion_263"]  # (B, T, 263)

    summary = load_json(summary_path) if summary_path.exists() else {}
    texts = summary.get("texts", [f"sample_{i}" for i in range(len(motion))])

    samples: list[dict] = []
    for i in range(len(motion)):
        samples.append({
            "seq_id": f"generated_{i:02d}",
            "text": texts[i] if i < len(texts) else "",
            "motion_263": motion[i],
            "joints_22": None,   # need to reconstruct
            "object_positions": None,
            "num_frames": int(motion[i].shape[0]),
        })
    return samples


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_visualization(
    samples: list[dict],
    output_dir: Path,
    source: str,
    fps: float,
) -> None:
    output_dir = ensure_dir(output_dir)
    index: list[dict] = []

    for sample in samples:
        seq_id = sample["seq_id"]
        # Prefer precomputed absolute joints; otherwise reconstruct from motion_263
        if sample["joints_22"] is not None:
            joints = sample["joints_22"]
        else:
            joints = motion_263_to_joints(sample["motion_263"], fps=fps)

        # Clip joints to actual number of frames
        n_frames = sample["num_frames"]
        joints = joints[:n_frames]

        obj_pos = sample.get("object_positions")
        if obj_pos is not None:
            obj_pos = obj_pos[:n_frames]

        title = f"[{source}] {seq_id}\n{sample['text'][:70]}"
        out_path = output_dir / f"{seq_id}.mp4"
        print(f"\nRendering {seq_id} ({n_frames} frames) → {out_path}")
        render_motion_video(
            joints, out_path, fps=fps, title=title,
            object_positions=obj_pos,
        )
        index.append({
            "seq_id": seq_id,
            "text": sample["text"],
            "num_frames": n_frames,
            "file": out_path.name,
            "source": source,
        })

    summary = {
        "timestamp": datetime.now().isoformat(),
        "source": source,
        "num_videos": len(index),
        "fps": fps,
        "videos": index,
    }
    save_json(output_dir / "summary.json", summary)
    print(f"\nRendered {len(index)} videos. Summary: {output_dir / 'summary.json'}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    subs = parser.add_subparsers(dest="source", required=True)

    # real
    p_real = subs.add_parser("real", help="Visualize real preprocessed sequences")
    p_real.add_argument("--data-dir", type=Path, required=True)
    p_real.add_argument("--seq-ids", nargs="*", default=None,
                        help="Specific sequence ids (default: first --num-samples)")
    p_real.add_argument("--num-samples", type=int, default=4)

    # generated
    p_gen = subs.add_parser("generated", help="Visualize generated motions from a run dir")
    p_gen.add_argument("--run-dir", type=Path, required=True,
                       help="A smoke-test or inference run directory containing generated.npz")

    for p in (p_real, p_gen):
        p.add_argument("--output-dir", type=Path, default=None,
                       help="Default: runs/visualizations/<timestamp>/")
        p.add_argument("--fps", type=float, default=20.0)
    return parser


def main() -> None:
    args = build_parser().parse_args()

    if args.output_dir is None:
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        output_dir = Path("runs/visualizations") / f"{timestamp}_{args.source}"
    else:
        output_dir = args.output_dir

    if args.source == "real":
        samples = load_real_samples(args.data_dir, args.seq_ids, args.num_samples)
    else:
        samples = load_generated_samples(args.run_dir)

    run_visualization(samples, output_dir, args.source, fps=args.fps)


if __name__ == "__main__":
    main()
