"""Motion visualization tool: render skeleton animations as MP4.

Supports two input sources:
    1. Real preprocessed dataset samples (from HOIDataset output)
    2. Generated motion from a smoke-test / inference run (.npz file)

Usage examples:

    # Visualize 4 real sequences from the preprocessed dataset
    python -m piano.inference.visualize_motion real \\
        --data-dir /media/.../datasets/omomo/piano \\
        --seq-ids sub10_clothesstand_000 sub11_largebox_003 sub12_monitor_001 \\
        --output-dir runs/visualizations/2026-04-19_real_samples

    # Visualize motion generated by the smoke test
    python -m piano.inference.visualize_motion generated \\
        --run-dir runs/checks/inference_smoke_test/2026-04-19_063940 \\
        --output-dir runs/visualizations/2026-04-19_smoke_generated
"""
from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import numpy as np

from piano.utils.io_utils import ensure_dir, load_json, save_json


# ---------------------------------------------------------------------------
# SMPL 22-joint skeleton for rendering
# ---------------------------------------------------------------------------

SKELETON_CONNECTIONS: list[tuple[int, int]] = [
    (0, 1), (0, 2), (0, 3),        # pelvis → left_hip, right_hip, spine1
    (1, 4), (2, 5), (3, 6),        # hips → knees, spine1 → spine2
    (4, 7), (5, 8), (6, 9),        # knees → ankles, spine2 → spine3
    (7, 10), (8, 11),              # ankles → feet
    (9, 12), (9, 13), (9, 14),     # spine3 → neck, collars
    (12, 15),                      # neck → head
    (13, 16), (14, 17),            # collars → shoulders
    (16, 18), (17, 19),            # shoulders → elbows
    (18, 20), (19, 21),            # elbows → wrists
]


# ---------------------------------------------------------------------------
# Motion decoding
# ---------------------------------------------------------------------------

def motion_263_to_joints(
    motion: np.ndarray,
    fps: float = 20.0,
    mean: np.ndarray | None = None,
    std: np.ndarray | None = None,
    world_R_y_angle: float | None = None,
    world_T_xz: np.ndarray | None = None,
) -> np.ndarray:
    """Reconstruct 22 absolute joint positions from HumanML3D 263-dim features.

    Delegates to MoMask's official ``recover_from_ric`` helper so the
    heading rotation, per-joint XZ offsets and absolute Y handling are
    all correct. Naive "subtract root, add height" code does not work
    because HumanML3D canonicalizes the heading before encoding.

    Parameters
    ----------
    motion : (T, 263) — HumanML3D features
    fps : unused (kept for API compatibility; recovery is frame-rate agnostic)
    mean, std : (263,) optional — denormalization stats applied before recovery
    world_R_y_angle, world_T_xz : optional — per-clip canonical→world
        transform (Y-axis rotation in radians, XZ translation 2-vector).
        When supplied, joints recovered in HumanML3D canonical frame are
        rotated by R_y around +Y and translated by (T_x, 0, T_z) so they
        sit in the SOURCE clip's world frame. This is what lets a
        canonical-frame generated motion be visualised together with a
        world-frame object trajectory (without it the body always starts
        at canonical origin while the object is metres away). Computed
        in :func:`scripts/stage_b_generator/qual_eval._get_canon_to_world_transform`.

    Returns
    -------
    joints : (T, 22, 3) — absolute joint positions, in world frame when
        ``world_R_y_angle`` + ``world_T_xz`` were provided, else in
        canonical frame.
    """
    import torch

    # MoMask's utils imports expect sys.path to include the backbone repo,
    # which the adapter already sets up when first imported.
    import piano.models.backbones.momask_adapter  # noqa: F401 — path side-effect
    from utils.motion_process import recover_from_ric

    if mean is not None and std is not None:
        motion = motion * std + mean

    data = torch.from_numpy(motion).float().unsqueeze(0)  # (1, T, 263)
    joints = recover_from_ric(data, joints_num=22)         # (1, T, 22, 3)
    joints = joints.squeeze(0).cpu().numpy().astype(np.float32)

    if world_R_y_angle is not None and world_T_xz is not None:
        cos_a = float(np.cos(world_R_y_angle))
        sin_a = float(np.sin(world_R_y_angle))
        R = np.array(
            [[cos_a, 0.0, sin_a],
             [0.0,   1.0, 0.0],
             [-sin_a, 0.0, cos_a]],
            dtype=np.float32,
        )
        joints = joints @ R.T            # (T, 22, 3)
        joints[..., 0] += float(world_T_xz[0])
        joints[..., 2] += float(world_T_xz[1])

    return joints


def _axis_angle_to_rotmat(aa: np.ndarray) -> np.ndarray:
    """Rodrigues: (3,) axis-angle to (3, 3) rotation matrix."""
    theta = np.linalg.norm(aa)
    if theta < 1e-8:
        return np.eye(3, dtype=np.float32)
    axis = aa / theta
    K = np.array(
        [
            [0, -axis[2], axis[1]],
            [axis[2], 0, -axis[0]],
            [-axis[1], axis[0], 0],
        ],
        dtype=np.float32,
    )
    return (
        np.eye(3, dtype=np.float32)
        + np.sin(theta) * K
        + (1 - np.cos(theta)) * K @ K
    )


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def render_motion_video(
    joints: np.ndarray,
    output_path: Path,
    fps: float = 20.0,
    title: str = "",
    object_positions: np.ndarray | None = None,
    object_rotations: np.ndarray | None = None,
    object_pc: np.ndarray | None = None,
    elev: float = 15.0,
    azim: float = -60.0,
    dpi: int = 80,
) -> None:
    """Render a skeleton animation (optionally with object) to MP4 or GIF.

    Parameters
    ----------
    joints : (T, 22, 3) — absolute joint positions
    output_path : where to save (.mp4 or .gif)
    fps : playback frame rate
    title : shown on the plot
    object_positions : (T, 3) — optional per-frame object center to overlay
    object_rotations : (T, 3) — optional per-frame object axis-angle rotation
    object_pc : (N, 3) — optional object point cloud in object-local frame;
        rendered at object_positions each frame, with rotation if provided.
    elev, azim : initial camera angles
    dpi : output resolution
    """
    import matplotlib.pyplot as plt
    from matplotlib.animation import FuncAnimation
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

    T = len(joints)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Precompute transformed object point cloud per frame (if available).
    obj_cloud_world: np.ndarray | None = None
    if object_pc is not None and object_positions is not None:
        T_obj = min(T, len(object_positions))
        if object_rotations is not None:
            T_obj = min(T_obj, len(object_rotations))
        N = object_pc.shape[0]
        obj_cloud_world = np.empty((T_obj, N, 3), dtype=np.float32)
        for t in range(T_obj):
            if object_rotations is not None:
                R = _axis_angle_to_rotmat(object_rotations[t])
                obj_cloud_world[t] = object_pc @ R.T + object_positions[t]
            else:
                obj_cloud_world[t] = object_pc + object_positions[t]

    # Compute axis limits covering all frames
    all_pos = [joints.reshape(-1, 3)]
    if obj_cloud_world is not None:
        all_pos.append(obj_cloud_world.reshape(-1, 3))
    elif object_positions is not None:
        all_pos.append(object_positions)
    all_pos = np.concatenate(all_pos, axis=0)
    center = all_pos.mean(axis=0)
    max_range = max((all_pos.max(axis=0) - all_pos.min(axis=0)).max() / 2 * 1.2, 0.5)

    fig = plt.figure(figsize=(7, 7))
    ax = fig.add_subplot(111, projection="3d")

    joint_scatter = ax.scatter([], [], [], c="blue", s=20)
    lines = [ax.plot([], [], [], c="gray", linewidth=1.5)[0] for _ in SKELETON_CONNECTIONS]
    object_scatter = None
    if obj_cloud_world is not None:
        object_scatter = ax.scatter([], [], [], c="red", s=2, marker="o", alpha=0.5)
    elif object_positions is not None:
        object_scatter = ax.scatter([], [], [], c="red", s=30, marker="^")

    ax.set_xlim(center[0] - max_range, center[0] + max_range)
    ax.set_ylim(center[2] - max_range, center[2] + max_range)
    ax.set_zlim(center[1] - max_range, center[1] + max_range)
    ax.set_xlabel("X")
    ax.set_ylabel("Z")
    ax.set_zlabel("Y")
    ax.view_init(elev=elev, azim=azim)
    title_artist = ax.set_title("")

    def update(t: int) -> list:
        artists: list = []
        # Plot body joints (swap axes so Y-up works in matplotlib 3D)
        joint_scatter._offsets3d = (
            joints[t, :, 0],
            joints[t, :, 2],
            joints[t, :, 1],
        )
        artists.append(joint_scatter)
        for (i, j), line in zip(SKELETON_CONNECTIONS, lines):
            line.set_data(
                [joints[t, i, 0], joints[t, j, 0]],
                [joints[t, i, 2], joints[t, j, 2]],
            )
            line.set_3d_properties([joints[t, i, 1], joints[t, j, 1]])
            artists.append(line)
        # Object marker (single point at COM, or transformed full point cloud)
        if object_scatter is not None:
            if obj_cloud_world is not None and t < len(obj_cloud_world):
                pos = obj_cloud_world[t]
                object_scatter._offsets3d = (pos[:, 0], pos[:, 2], pos[:, 1])
            elif object_positions is not None and t < len(object_positions):
                p = object_positions[t]
                object_scatter._offsets3d = ([p[0]], [p[2]], [p[1]])
            artists.append(object_scatter)

        title_artist.set_text(f"{title}\nFrame {t+1}/{T} ({t/fps:.2f}s)")
        artists.append(title_artist)
        return artists

    anim = FuncAnimation(
        fig, update, frames=T, interval=1000 / fps, blit=False, repeat=False,
    )

    # Save: try ffmpeg first for mp4, fall back to pillow for gif
    suffix = output_path.suffix.lower()
    try:
        if suffix == ".mp4":
            anim.save(str(output_path), writer="ffmpeg", fps=fps, dpi=dpi)
        else:
            anim.save(str(output_path), writer="pillow", fps=fps, dpi=dpi)
    except Exception as e:
        # ffmpeg unavailable — fall back to gif
        gif_path = output_path.with_suffix(".gif")
        print(f"  [warn] {e}; falling back to {gif_path}")
        anim.save(str(gif_path), writer="pillow", fps=fps, dpi=dpi)
        output_path = gif_path
    finally:
        plt.close(fig)

    print(f"  Saved: {output_path}")


# ---------------------------------------------------------------------------
# Input source adapters
# ---------------------------------------------------------------------------

def load_real_samples(
    data_dir: Path, seq_ids: list[str] | None, num_samples: int,
) -> list[dict]:
    """Load preprocessed motion sequences from the PIANO-format dataset."""
    metadata = load_json(data_dir / "metadata.json")
    if seq_ids:
        wanted = set(seq_ids)
        selected = [m for m in metadata if m["seq_id"] in wanted]
        if len(selected) != len(seq_ids):
            missing = wanted - {m["seq_id"] for m in selected}
            print(f"  [warn] missing seq_ids: {missing}")
    else:
        selected = metadata[:num_samples]

    samples: list[dict] = []
    for meta in selected:
        npz_path = data_dir / "motions" / f"{meta['seq_id']}.npz"
        if not npz_path.exists():
            print(f"  [warn] {npz_path} not found, skipping")
            continue
        data = np.load(npz_path)
        samples.append({
            "seq_id": meta["seq_id"],
            "text": meta.get("text", ""),
            "object_id": meta.get("object_id", ""),
            "motion_263": data["motion_263"],
            "joints_22": data["joints_22"],        # absolute joints from preprocessing
            "object_positions": data.get("object_positions") if "object_positions" in data.files else None,
            "object_rotations": data.get("object_rotations") if "object_rotations" in data.files else None,
            "object_pc": (
                np.load(data_dir / "objects" / f"{meta['object_id']}.npy").astype(np.float32)
                if meta.get("object_id") and (data_dir / "objects" / f"{meta['object_id']}.npy").exists()
                else None
            ),
            "num_frames": int(data["motion_263"].shape[0]),
        })
    return samples


def load_generated_samples(run_dir: Path) -> list[dict]:
    """Load generated motions from a smoke-test or qual-eval run directory.

    Reads ``generated.npz``. Recognised optional keys (added per
    qual_eval.py's overlay support, 2026-04-27):

        - ``object_positions`` — (B, T, 3) per-frame object center
        - ``object_rotations`` — (B, T, 3) per-frame axis-angle
        - ``object_pc``        — (B, N, 3) per-clip object point cloud
                                 (fixed N, in object-local frame)

    All four are optional; missing ones translate to ``None`` on the
    sample so :func:`render_motion_video` can ignore them. The
    summary's ``seq_ids`` field (when present) is preferred over
    auto-generated ``generated_NN`` so the rendered file names match
    the source clips.
    """
    npz_path = run_dir / "generated.npz"
    summary_path = run_dir / "summary.json"
    if not npz_path.exists():
        raise FileNotFoundError(f"No generated.npz in {run_dir}")
    data = np.load(npz_path)
    motion = data["motion_263"]  # (B, T, 263)
    object_positions = data["object_positions"] if "object_positions" in data.files else None
    object_rotations = data["object_rotations"] if "object_rotations" in data.files else None
    object_pcs = data["object_pc"] if "object_pc" in data.files else None
    world_R_y = data["world_R_y_angle"] if "world_R_y_angle" in data.files else None
    world_T_xz = data["world_T_xz"] if "world_T_xz" in data.files else None

    summary = load_json(summary_path) if summary_path.exists() else {}
    texts = summary.get("texts", [f"sample_{i}" for i in range(len(motion))])
    seq_lens = summary.get("seq_lens", [motion.shape[1]] * len(motion))
    seq_ids = summary.get("seq_ids", [f"generated_{i:02d}" for i in range(len(motion))])

    samples: list[dict] = []
    for i in range(len(motion)):
        samples.append({
            "seq_id": seq_ids[i] if i < len(seq_ids) else f"generated_{i:02d}",
            "text": texts[i] if i < len(texts) else "",
            "motion_263": motion[i],
            "joints_22": None,          # need to reconstruct from motion_263
            "object_positions": object_positions[i] if object_positions is not None else None,
            "object_rotations": object_rotations[i] if object_rotations is not None else None,
            "object_pc": object_pcs[i] if object_pcs is not None else None,
            "world_R_y_angle": float(world_R_y[i]) if world_R_y is not None else None,
            "world_T_xz": world_T_xz[i] if world_T_xz is not None else None,
            "num_frames": int(seq_lens[i] if i < len(seq_lens) else motion[i].shape[0]),
        })
    return samples


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_visualization(
    samples: list[dict],
    output_dir: Path,
    source: str,
    fps: float,
    mean: np.ndarray | None = None,
    std: np.ndarray | None = None,
    use_recovery: bool = False,
) -> None:
    """Render motion videos.

    Parameters
    ----------
    use_recovery : if True, always decode via ``motion_263_to_joints``
        (MoMask's ``recover_from_ric``). For real samples this provides
        an encode → decode round-trip sanity check: if the new encoder
        produced HumanML3D-compatible features, the recovered skeleton
        should look normal (in canonical coordinate frame, not world).
        If False (default), real uses precomputed joints_22 directly.
    """
    output_dir = ensure_dir(output_dir)
    index: list[dict] = []

    for sample in samples:
        seq_id = sample["seq_id"]
        # Default: real uses precomputed joints_22 (world frame); generated
        # uses recover_from_ric (canonical frame). Override with use_recovery
        # to force recovery path on real samples for round-trip validation.
        if sample["joints_22"] is not None and not use_recovery:
            joints = sample["joints_22"]
        else:
            joints = motion_263_to_joints(
                sample["motion_263"], fps=fps, mean=mean, std=std,
                world_R_y_angle=sample.get("world_R_y_angle"),
                world_T_xz=sample.get("world_T_xz"),
            )

        # Clip joints to actual number of frames
        n_frames = sample["num_frames"]
        joints = joints[:n_frames]

        obj_pos = sample.get("object_positions")
        obj_rot = sample.get("object_rotations")
        obj_pc = sample.get("object_pc")
        if obj_pos is not None:
            obj_pos = obj_pos[:n_frames]
        if obj_rot is not None:
            obj_rot = obj_rot[:n_frames]

        title = f"[{source}] {seq_id}\n{sample['text'][:70]}"
        out_path = output_dir / f"{seq_id}.mp4"
        print(f"\nRendering {seq_id} ({n_frames} frames) → {out_path}")
        render_motion_video(
            joints, out_path, fps=fps, title=title,
            object_positions=obj_pos,
            object_rotations=obj_rot,
            object_pc=obj_pc,
        )
        index.append({
            "seq_id": seq_id,
            "text": sample["text"],
            "object_id": sample.get("object_id", ""),
            "num_frames": n_frames,
            "file": out_path.name,
            "source": source,
        })

    summary = {
        "timestamp": datetime.now().isoformat(),
        "source": source,
        "num_videos": len(index),
        "fps": fps,
        "videos": index,
    }
    save_json(output_dir / "summary.json", summary)
    print(f"\nRendered {len(index)} videos. Summary: {output_dir / 'summary.json'}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    subs = parser.add_subparsers(dest="source", required=True)

    # real
    p_real = subs.add_parser("real", help="Visualize real preprocessed sequences")
    p_real.add_argument("--data-dir", type=Path, required=True)
    p_real.add_argument("--seq-ids", nargs="*", default=None,
                        help="Specific sequence ids (default: first --num-samples)")
    p_real.add_argument("--num-samples", type=int, default=4)

    # generated
    p_gen = subs.add_parser("generated", help="Visualize generated motions from a run dir")
    p_gen.add_argument("--run-dir", type=Path, required=True,
                       help="A smoke-test or inference run directory containing generated.npz")
    p_gen.add_argument("--seq-ids", nargs="*", default=None,
                       help="Render only these sequence ids (default: render all clips). "
                            "Use this to spot-check a focused subset (worst clips, "
                            "historical hard cases, etc.) instead of rendering the full "
                            "80-clip eval matrix.")
    p_gen.add_argument("--num-samples", type=int, default=None,
                       help="If --seq-ids is not set, render only the first N clips. "
                            "Default: render all.")

    for p in (p_real, p_gen):
        p.add_argument("--output-dir", type=Path, default=None,
                       help="Default: runs/visualizations/<timestamp>/")
        p.add_argument("--fps", type=float, default=20.0)
        p.add_argument("--mean", type=Path, default=None,
                       help="HumanML3D mean.npy. ONLY pass this when the source "
                            "motion_263 is in NORMALIZED scale. qual_eval.py and "
                            "gt_vq_roundtrip.py already denormalize before saving "
                            "generated.npz, so passing --mean/--std on those "
                            "outputs DOUBLE-denormalizes and squashes root motion "
                            "to dataset mean (all bodies look like 'walk forward "
                            "in +z at 0.17 m/s'). Pass only if you have a custom "
                            "pipeline that saves normalized motion_263.")
        p.add_argument("--std", type=Path, default=None,
                       help="HumanML3D std.npy — paired with --mean. Same caveat: "
                            "do not pass on qual_eval / gt_vq_roundtrip outputs.")
        p.add_argument("--use-recovery", action="store_true",
                       help="Force motion_263 → recover_from_ric path even for "
                            "real samples. Useful for validating that the "
                            "encoder round-trips correctly.")
    return parser


def main() -> None:
    args = build_parser().parse_args()

    if args.output_dir is None:
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        output_dir = Path("runs/visualizations") / f"{timestamp}_{args.source}"
    else:
        output_dir = args.output_dir

    mean = np.load(args.mean).astype(np.float32) if args.mean else None
    std = np.load(args.std).astype(np.float32) if args.std else None

    if args.source == "real":
        samples = load_real_samples(args.data_dir, args.seq_ids, args.num_samples)
    else:
        samples = load_generated_samples(args.run_dir)
        if args.seq_ids:
            wanted = set(args.seq_ids)
            selected = [s for s in samples if s["seq_id"] in wanted]
            missing = wanted - {s["seq_id"] for s in selected}
            if missing:
                print(f"  [warn] missing seq_ids in generated.npz: {sorted(missing)}")
            samples = selected
        elif args.num_samples is not None:
            samples = samples[: args.num_samples]

    run_visualization(
        samples, output_dir, args.source, fps=args.fps,
        mean=mean, std=std, use_recovery=args.use_recovery,
    )


if __name__ == "__main__":
    main()
