"""Generate Round-29 Tier-2 ablation configs from the a0 baseline.

Tier-2 ablations test three design-philosophy mismatches identified in
the audit at `analyses/2026-05-26_round29_cond_and_loss_audit.md`:

  1. init_pose (frame-0 SMPL-22 joints) — duplicates info already in
     motion[0] + stage1_coarse[0]; plus a train/inference distribution
     leak (training sees clean GT frame 0, inference's Stage-1 frame 0
     is noisy).
  2. text (CLIP per-token + text_xattn) — InterAct text labels are
     object names that object_tokens already encodes; three cross-
     attentions per block is more than needed.
  3. pos_loss_weight (dense FK position MSE, weight 5) — overlaps
     mse_x0 (motion_135 channels) and loss_anchor_joint_pos (active
     parts, weight 10).

Each ablation is a single-variable change from r29_a0_input_add (FULL-DENSE
+ J0 input_add). Same training subset, same epochs, same R29 4-family
content. Compare A0 baseline diag results vs each ablation's diag results
on the same 48-clip subset.

Outputs:
    configs/training/anchordiff_r29_t2_no_init_pose.yaml
    configs/training/anchordiff_r29_t2_no_text.yaml
    configs/training/anchordiff_r29_t2_no_dense_pos.yaml
    analyses/round29_tier2_ablation_manifest.json
    analyses/round29_tier2_ablation_manifest.md

Usage:
    python scripts/stage_b_generator/round29_make_tier2_ablation_configs.py
    python scripts/stage_b_generator/round29_make_tier2_ablation_configs.py \
        --data-root /media/.../piano_official_process_4
"""
from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG_DIR = ROOT / "configs" / "training"
DEFAULT_ANALYSES_DIR = ROOT / "analyses"
DEFAULT_DATA_ROOT = "E:/Project/Datasets/InterAct/piano_official_process_4"
DEFAULT_SUBSET_FILE = "analyses/round27_tier0_train_indices_48_balanced.json"
DATASET_SUBSET_NAMES: tuple[str, ...] = (
    "chairs", "imhd", "neuraldome", "omomo_correct_v2",
)


@dataclass(slots=True)
class T2Variant:
    variant_id: str
    purpose: str
    # Three knobs vs a0 baseline; default = a0 baseline value.
    init_pose_dim: int = 66
    text_dim: int = 512
    pos_loss_weight: float = 5.0
    hand_endpoint_weight: float = 2.0
    foot_endpoint_weight: float = 2.0
    diagnostics: tuple[str, ...] = field(default_factory=lambda: (
        "sustained_contact", "gait", "body_action",
    ))


VARIANTS: list[T2Variant] = [
    T2Variant(
        variant_id="r29_t2_no_init_pose",
        purpose=(
            "Drop the frame-0 init-pose sequence token (init_pose_dim=0). "
            "Tests whether init_pose adds information beyond motion[0] + "
            "stage1_coarse[0] and whether the train/inference frame-0 "
            "distribution leak matters."
        ),
        init_pose_dim=0,
    ),
    T2Variant(
        variant_id="r29_t2_no_text",
        purpose=(
            "Drop CLIP text + text_xattn (text_dim=0). Tests whether the "
            "InterAct text labels add anything that object_tokens doesn't "
            "already encode."
        ),
        text_dim=0,
    ),
    T2Variant(
        variant_id="r29_t2_no_dense_pos",
        purpose=(
            "Drop the dense FK position loss (pos_loss_weight=0). Tests "
            "whether the dense 22-joint × all-frames FK MSE is still useful "
            "given mse_x0 (motion_135 channels) and loss_anchor_joint_pos "
            "(weight 10) already supervise joints. Disables hand/foot "
            "endpoint weights too (they are only applied when pos_loss > 0)."
        ),
        pos_loss_weight=0.0,
        hand_endpoint_weight=1.0,
        foot_endpoint_weight=1.0,
    ),
]


def _render_datasets_block(data_root: str) -> str:
    stripped = data_root.rstrip("/").rstrip("\\")
    lines: list[str] = []
    for sub in DATASET_SUBSET_NAMES:
        lines.append(f'    - name: "{sub}"')
        lines.append(f'      root: "{stripped}/{sub}"')
    return "\n".join(lines)


def _render_yaml(v: T2Variant, *, subset_file: str, data_root: str) -> str:
    run_name = f"stageB_anchordiff_{v.variant_id}"
    return f"""# Round-29 Tier-2 {v.variant_id}: {v.purpose}
#
# Generated by scripts/stage_b_generator/round29_make_tier2_ablation_configs.py.
# Single-variable ablation vs r29_a0_input_add baseline (FULL-DENSE + J0 input_add).

model:
  cfg_drop_prob: 0.15
  diffusion:
    num_steps: 1000
    schedule: "cosine"
    prediction_target: "x0"
  z_int:
    num_parts: 5
    phase_classes: 3
    support_classes: 3
  denoiser:
    motion_dim: 135
    object_traj_dim: 9
    init_pose_dim: {v.init_pose_dim}
    text_dim: {v.text_dim}
    object_token_dim: 256
    object_num_tokens: 128
    d_model: 512
    n_layers: 8
    n_heads: 4
    ff_mult: 4
    dropout: 0.1
    stage1_coarse_dim: 23
    # R29 typed condition injection (same as a0 baseline).
    use_round29_cond_injection: true
    r29_coarse_extra_dim: 18
    r29_interaction_dim: 8
    r29_support_dim: 13
    r29_body_refine_dim: 20
    r29_injection_mode: "input_add"
    r29_gate_bias_init: -1.0
    r29_per_family_modes: null
    r29_zero_init_adapters: true
  object_encoder:
    num_input_points: 1024
    num_output_tokens: 128
    feature_dim: 256
  text_encoder:
    clip_version: "ViT-B/32"
    download_root: "cache/clip"

data:
  datasets:
{_render_datasets_block(data_root)}
  pseudo_label_dir: null
  pseudo_label_subdir: "pseudo_labels/v18_h10_f05_pelvis20_official_semantic_marker"
  max_seq_length: 196
  support_collapse_hand_support: true
  motion_representation: "smpl_pose_135_plan"
  force_world_frame: true
  subsample_n_per_object: null
  overfit_n_clips: 0
  stage1_coarse_cache_root: "cache/stage1_coarse_v1_full"
  subset_indices_file: "{subset_file}"
  surface_temporal_aux_fields: true
  # R29 4-family content (same as a0 baseline: FULL-DENSE).
  r29_coarse_variant: "C41-current"
  r29_interaction_variant: "I3-contact-offset-masked"
  r29_support_variant: "S4-S1-phase-footstep"
  r29_body_variant: "B4-lowpass-residual-mask"
  r29_body_coord_frame: null
  r29_body_energy_threshold: 0.05
  r29_body_lowpass_window: 9
  r29_hand_offset_clamp_m: 2.0
  subject_split:
    enabled: true
    train_pct: 85
    val_pct: 15
    seed: 42
  augmentation:
    enabled: false
    mirror_prob: 0.0
    rotate_around_y_prob: 0.0
    pc_jitter_std: 0.0

training:
  batch_size: 8
  num_epochs: 300
  num_workers: 4
  seed: 42
  stage1_coarse_noise_std: 0.0
  optimizer:
    name: "adamw"
    lr: 5.0e-5
    weight_decay: 0.01
    betas: [0.9, 0.999]
  scheduler:
    name: "cosine"
    warmup_steps: 50
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  mixed_precision: "bf16"
  val_on_train_subset: true
  val_every_epochs: 50
  val_best_key: "loss_anchor_joint_pos"

loss:
  anchor_weight: 0.0
  contact_threshold: 0.5
  stable_root_vel_weight: 0.5
  stable_root_acc_weight: 0.25
  stable_support_erode: 4
  stable_local_vel_cm_weight: 0.05
  stable_local_speed_moment_weight: 0.02
  hand_endpoint_weight: {v.hand_endpoint_weight}
  foot_endpoint_weight: {v.foot_endpoint_weight}
  pos_loss_weight: {v.pos_loss_weight}
  anchor_joint_pos_weight: 10.0
  anchor_joint_vel_weight: 2.0
  anchor_joint_part_weights: [2.0, 2.0, 0.0, 0.0, 0.5]
  use_min_snr_weighting: true
  min_snr_gamma: 5.0
  world_joint_velocity_weight: 1.0
  temporal_interaction:
    contact_rel_offset_weight: 0.0
    contact_drift_weight: 0.0
    contact_tracking_weight: 0.0
    gait_both_airborne_weight: 0.0
    gait_stance_velocity_weight: 0.0
    hint_contact_consistency_weight: 0.0
    body_action_consistency_weight: 0.0
    contact_threshold: 0.5
    contact_rel_clamp_m: 2.0
    tracking_margin_m: 0.03
    tracking_min_obj_disp_m: 0.05
    floor_quantile: 0.05
    grounded_threshold_above_floor_m: 0.10
    grounded_softness_m: 0.03

logging:
  project: "piano"
  run_name: "{run_name}"
  log_every_n_steps: 10
  save_every_n_epochs: 50

output_dir: "runs/training/{run_name}"
"""


def _to_posix_relpath(p: str | Path, root: Path) -> str:
    s = str(p)
    if not s:
        return s
    p_obj = Path(s)
    try:
        rel = p_obj.resolve().relative_to(root.resolve())
        return rel.as_posix()
    except (ValueError, OSError):
        return p_obj.as_posix() if not p_obj.is_absolute() else s


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate R29 Tier-2 ablation configs (init_pose / text / dense_pos).",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--data-root",
        default=os.environ.get("DATASETS_ROOT", DEFAULT_DATA_ROOT),
        help=(
            "Root directory containing the four InterAct subsets. "
            "On the Linux server pass --data-root /media/.../piano_official_process_4 "
            "or export DATASETS_ROOT=..."
        ),
    )
    parser.add_argument(
        "--subset-file", default=DEFAULT_SUBSET_FILE,
        help="Subset JSON consumed by trainer + diagnostics.",
    )
    parser.add_argument(
        "--config-dir", default=str(DEFAULT_CONFIG_DIR),
    )
    parser.add_argument(
        "--analyses-dir", default=str(DEFAULT_ANALYSES_DIR),
    )
    args = parser.parse_args()

    config_dir = Path(args.config_dir)
    analyses_dir = Path(args.analyses_dir)
    subset_file = _to_posix_relpath(args.subset_file, ROOT)

    rows: list[dict] = []
    for v in VARIANTS:
        out_path = config_dir / f"anchordiff_{v.variant_id}.yaml"
        content = _render_yaml(v, subset_file=subset_file, data_root=args.data_root)
        canonical_cfg = f"configs/training/anchordiff_{v.variant_id}.yaml"
        row = {
            "variant_id": v.variant_id,
            "group": "Tier2",
            "purpose": v.purpose,
            # Baseline comparison: r29_a0_input_add must be already trained.
            "baseline_variant_id": "r29_a0_input_add",
            "knobs": {
                "init_pose_dim": v.init_pose_dim,
                "text_dim": v.text_dim,
                "pos_loss_weight": v.pos_loss_weight,
                "hand_endpoint_weight": v.hand_endpoint_weight,
                "foot_endpoint_weight": v.foot_endpoint_weight,
            },
            "subset_kind": "balanced",
            "subset_file": subset_file,
            "num_epochs": 300,
            "seed": 42,
            "val_on_train_subset": True,
            "config_path": canonical_cfg,
            "output_dir": f"runs/training/stageB_anchordiff_{v.variant_id}",
            "diagnostics": list(v.diagnostics),
        }
        rows.append(row)
        if args.dry_run:
            print(f"DRY-RUN would write: {out_path}  ({len(content)} bytes)")
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            print(f"wrote {out_path}")

    manifest_json = analyses_dir / "round29_tier2_ablation_manifest.json"
    manifest_md = analyses_dir / "round29_tier2_ablation_manifest.md"

    md_lines: list[str] = [
        "# Round-29 Tier-2 ablation manifest",
        "",
        "Each variant is a single-variable change from `r29_a0_input_add` (FULL-DENSE + J0).",
        "",
        "| variant | knob | value | baseline value |",
        "| --- | --- | --- | --- |",
        "| `r29_t2_no_init_pose` | `init_pose_dim` | `0` | `66` |",
        "| `r29_t2_no_text` | `text_dim` | `0` | `512` |",
        "| `r29_t2_no_dense_pos` | `pos_loss_weight` | `0.0` | `5.0` |",
        "| | `hand_endpoint_weight` | `1.0` | `2.0` |",
        "| | `foot_endpoint_weight` | `1.0` | `2.0` |",
        "",
        "Compare each variant's three diag outputs against `r29_a0_input_add`.",
    ]
    if args.dry_run:
        print(f"DRY-RUN would write: {manifest_json}")
        print(f"DRY-RUN would write: {manifest_md}")
    else:
        analyses_dir.mkdir(parents=True, exist_ok=True)
        manifest_json.write_text(
            json.dumps({"variants": rows, "data_root": args.data_root}, indent=2),
            encoding="utf-8",
        )
        manifest_md.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
        print(f"wrote {manifest_json}")
        print(f"wrote {manifest_md}")
    print(f"\n{len(rows)} Tier-2 variant(s) emitted.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
