#!/usr/bin/env bash
# Round-29 loss-strategy full-data visual review launcher.
#
# Renders N clips × 4 R29 ckpts on the val 48-clip balanced subset, then
# tarballs the result for scp back to local.
#
# Why 4 ckpts (within-matrix, no v27 — v27 ckpt is no longer on server):
#   The R29 verdict (analyses/2026-05-27_round29_loss_strategy_full_data_verdict.md)
#   said:
#     - a3_baseline_from_scratch    val drift 13.37 cm   best contact + body
#     - a2_baseline_from_scratch    val drift 14.22 cm
#     - a2_anchor2_mixed            val drift 16.34 cm   best L_R_corr -0.18
#     - a3_anchor2_mixed            val drift 16.66 cm
#   Visual review on the same val subset should show:
#     1. baseline_from_scratch vs anchor2_mixed: does the relative-loss
#        family visually look "looser" on contact (hand let-go halfway up
#        the box) while showing better gait alternation?
#     2. A2 vs A3 within loss-strategy: does input_add (A3) visibly help
#        contact vs adapter-only (A2)?
#
# DEFAULT N_CLIPS=16. Override via env if you want a different size.
#
# Wall-clock budget (rough, ~30s/clip per ckpt on 1 GPU):
#   N_CLIPS=16, 4 ckpts, dual-GPU pairwise: ~10-12 min total
#   N_CLIPS=16, single-GPU sequential:       ~20-25 min total
#   PACK:                                     ~30 s
#
# Prerequisites on the Linux server:
#   1. git pull (must include the Round-29 commits + this script)
#   2. ckpts present at:
#        runs/training/stageB_anchordiff_r29_lsf_a2_baseline_from_scratch/best_val.pt
#        runs/training/stageB_anchordiff_r29_lsf_a3_baseline_from_scratch/best_val.pt
#        runs/training/stageB_anchordiff_r29_lsf_a2_anchor2_mixed/best_val.pt
#        runs/training/stageB_anchordiff_r29_lsf_a3_anchor2_mixed/best_val.pt
#   3. _local.yaml configs (Linux dataset paths):
#        bash scripts/stage_b_generator/run_round29_loss_strategy_make_local_configs.sh
#      (created alongside this launcher, mirrors run_round28_make_local_configs.sh)
#   4. val 48-clip balanced selection JSON:
#        analyses/round29_val_diag_indices_48_balanced.json
#      (auto-generated by round29_build_val_diag_subset.py; if absent the
#       launcher rebuilds it inline.)
#
# Usage:
#   bash scripts/stage_b_generator/run_round29_loss_strategy_visual_review.sh
#
#   # Render only 8 clips (faster):
#   ROUND29_VIS_N_CLIPS=8 bash scripts/stage_b_generator/run_round29_loss_strategy_visual_review.sh
#
#   # Render the full 48-clip val subset:
#   ROUND29_VIS_N_CLIPS=48 bash scripts/stage_b_generator/run_round29_loss_strategy_visual_review.sh
#
#   # Use train subset instead of val:
#   ROUND29_VIS_BUCKET=train SEL_JSON=analyses/round27_tier0_train_indices_48_balanced.json \
#     bash scripts/stage_b_generator/run_round29_loss_strategy_visual_review.sh
#
#   # Single-GPU fallback (cuda:0, sequential):
#   ROUND29_VIS_SINGLE_GPU=1 bash scripts/stage_b_generator/run_round29_loss_strategy_visual_review.sh
#
#   # Render only a subset of variants (any subset of the 4):
#   ROUND29_VIS_VARIANTS="a3_baseline_from_scratch a2_anchor2_mixed" \
#     bash scripts/stage_b_generator/run_round29_loss_strategy_visual_review.sh
set -euo pipefail
cd "$(dirname "$0")/../.."

LOG_DIR="runs/round29_loss_strategy_visual_review"
mkdir -p "${LOG_DIR}"

# ---------- env overrides ----------
SEL_JSON="${SEL_JSON:-analyses/round29_val_diag_indices_48_balanced.json}"
N_CLIPS="${ROUND29_VIS_N_CLIPS:-16}"
SINGLE_GPU="${ROUND29_VIS_SINGLE_GPU:-0}"
BUCKET="${ROUND29_VIS_BUCKET:-val}"
DEFAULT_VARIANTS=(
    a2_baseline_from_scratch
    a3_baseline_from_scratch
    a2_anchor2_mixed
    a3_anchor2_mixed
)
if [[ -n "${ROUND29_VIS_VARIANTS:-}" ]]; then
    # shellcheck disable=SC2206
    VARIANTS=(${ROUND29_VIS_VARIANTS})
else
    VARIANTS=("${DEFAULT_VARIANTS[@]}")
fi

# ---------- selection JSON ----------
if [[ ! -e "${SEL_JSON}" ]]; then
    if [[ "${BUCKET}" == "val" && "${SEL_JSON}" == *round29_val_diag_indices_48_balanced.json ]]; then
        echo "Selection JSON missing; rebuilding via round29_build_val_diag_subset.py"
        python scripts/stage_b_generator/round29_build_val_diag_subset.py \
            --config "configs/training/anchordiff_r29_lsf_a3_baseline_from_scratch_local.yaml"
    else
        echo "ERROR: missing selection JSON: ${SEL_JSON}"
        echo "  For val:   python scripts/stage_b_generator/round29_build_val_diag_subset.py --config <any R29 _local.yaml>"
        echo "  For train: use analyses/round27_tier0_train_indices_48_balanced.json"
        exit 1
    fi
fi

# ---------- preflight ----------
for V in "${VARIANTS[@]}"; do
    CFG="configs/training/anchordiff_r29_lsf_${V}_local.yaml"
    CKPT="runs/training/stageB_anchordiff_r29_lsf_${V}/best_val.pt"
    if [[ ! -e "${CFG}" ]]; then
        echo "ERROR: missing config: ${CFG}"
        echo "  Run: bash scripts/stage_b_generator/run_round29_loss_strategy_make_local_configs.sh"
        exit 1
    fi
    if [[ ! -e "${CKPT}" ]]; then
        echo "ERROR: missing ckpt: ${CKPT}"
        exit 1
    fi
done

SEL_N=$(python -c "import json; d=json.load(open('${SEL_JSON}')); print(d.get('n_clips') or d.get('n_found') or len(d.get('selected') or d.get('clips') or []))")
echo "Selection: ${SEL_N} clips available; rendering first ${N_CLIPS} from ${BUCKET} bucket"
echo "Variants: ${VARIANTS[*]}"

# ---------- helpers ----------
run_step_bg() {
    local NAME="$1"; shift
    local GPU="$1"; shift
    local LOG="${LOG_DIR}/${NAME}.log"
    local T0
    T0=$(date +%s)
    {
        echo "================================================================"
        echo "[$(date '+%F %T')] BG-START ${NAME} on cuda:${GPU}"
        echo "    log: ${LOG}"
        echo "================================================================"
        env CUDA_VISIBLE_DEVICES="${GPU}" \
            PYTHONUNBUFFERED=1 PYTHONIOENCODING=utf-8 "$@" 2>&1
        local T1
        T1=$(date +%s)
        echo "[$(date '+%F %T')] BG-DONE ${NAME} in $((T1-T0))s"
    } > "${LOG}" 2>&1
}

run_step_fg() {
    local NAME="$1"; shift
    local GPU="$1"; shift
    local LOG="${LOG_DIR}/${NAME}.log"
    local T0
    T0=$(date +%s)
    echo
    echo "================================================================"
    echo "[$(date '+%F %T')] START ${NAME} on cuda:${GPU}"
    echo "    log: ${LOG}"
    echo "================================================================"
    env CUDA_VISIBLE_DEVICES="${GPU}" \
        PYTHONUNBUFFERED=1 PYTHONIOENCODING=utf-8 "$@" 2>&1 | tee "${LOG}"
    local T1
    T1=$(date +%s)
    echo "[$(date '+%F %T')] DONE ${NAME} in $((T1-T0))s"
}

render_one() {
    local NAME="$1"; local GPU="$2"; local CFG="$3"; local CKPT="$4"; local OUT="$5"; local MODE="$6"
    local RUN_FN="run_step_fg"
    if [[ "${MODE}" == "bg" ]]; then RUN_FN="run_step_bg"; fi
    mkdir -p "${OUT}"
    "${RUN_FN}" "render_${NAME}" "${GPU}" \
        conda run --no-capture-output -n piano python -u \
            scripts/stage_b_generator/render_round24_visual_review.py \
            --config "${CFG}" --ckpt "${CKPT}" --output-dir "${OUT}" \
            --bucket "${BUCKET}" --n-clips "${N_CLIPS}" \
            --selection-json "${SEL_JSON}" \
            --cfg-scale 1.0 --seed 42
}

OUT_ROOT="analyses/round29_loss_strategy_visual_review"
mkdir -p "${OUT_ROOT}"

# ---------- render ----------
if [[ "${SINGLE_GPU}" == "1" ]]; then
    echo
    echo "================================================================"
    echo "[$(date '+%F %T')] SINGLE-GPU RENDER (cuda:0, sequential ${#VARIANTS[@]} ckpts)"
    echo "================================================================"
    for V in "${VARIANTS[@]}"; do
        CFG="configs/training/anchordiff_r29_lsf_${V}_local.yaml"
        CKPT="runs/training/stageB_anchordiff_r29_lsf_${V}/best_val.pt"
        OUT="${OUT_ROOT}/${V}"
        render_one "${V}" 0 "${CFG}" "${CKPT}" "${OUT}" fg
    done
else
    echo
    echo "================================================================"
    echo "[$(date '+%F %T')] DUAL-GPU RENDER: pairwise (cuda:0 || cuda:1)"
    echo "================================================================"
    i=0
    PIDS=()
    NAMES=()
    for V in "${VARIANTS[@]}"; do
        CFG="configs/training/anchordiff_r29_lsf_${V}_local.yaml"
        CKPT="runs/training/stageB_anchordiff_r29_lsf_${V}/best_val.pt"
        OUT="${OUT_ROOT}/${V}"
        GPU=$((i % 2))
        render_one "${V}" "${GPU}" "${CFG}" "${CKPT}" "${OUT}" bg &
        PIDS+=($!)
        NAMES+=("${V}")
        i=$((i + 1))
        # Drain every pair so we don't run more than 2 concurrent renders.
        if (( i % 2 == 0 )); then
            for j in 0 1; do
                wait "${PIDS[j]}" || echo "  ${NAMES[j]} exited non-zero"
            done
            PIDS=()
            NAMES=()
        fi
    done
    # Drain any leftover (odd number of variants).
    for k in "${!PIDS[@]}"; do
        wait "${PIDS[k]}" || echo "  ${NAMES[k]} exited non-zero"
    done
fi

# ---------- pack ----------
STAMP=$(date +%Y%m%d_%H%M%S)
TARBALL="round29_loss_strategy_visual_review_${STAMP}.tar.gz"
echo
echo "================================================================"
echo "[$(date '+%F %T')] PACK -> ${TARBALL}"
echo "================================================================"
tar -czf "${TARBALL}" -C analyses "$(basename "${OUT_ROOT}")"
SIZE=$(du -h "${TARBALL}" | cut -f1)
echo "wrote ${TARBALL}  (${SIZE})"

echo
echo "================================================================"
echo "Round-29 loss-strategy visual review complete."
echo "Outputs:"
for V in "${VARIANTS[@]}"; do
    echo "  ${OUT_ROOT}/${V}/clip*_{gt,pred}.mp4 + summary.md"
done
echo "Logs:    ${LOG_DIR}/render_*.log"
echo "Tarball: ${TARBALL}"
echo
echo "scp back:  scp <server>:$(pwd)/${TARBALL} ."
echo "Then on local:  tar -xzf ${TARBALL} -C analyses/"
echo "================================================================"
