#!/usr/bin/env bash
# Round-27 Tier-0 visual review launcher.
#
# Renders N clips × 3 ckpts (baseline v27 / T0-A3 contact-winner /
# T0-B1 gait-winner) using scripts/stage_b_generator/render_round24_visual_review.py
# with the same balanced 48-clip selection JSON the Tier-0 EVAL used.
#
# Why 3 ckpts:
#   The Tier-0 metric verdict said "T0-A wins contact, T0-B wins gait,
#   T0-AB underperforms". Visual review on the SAME train clips should
#   confirm:
#     1. v27 still shows the user-described hand-letting-go-halfway-up-
#        the-box + both-feet-floating failures.
#     2. T0-A3 visually fixes the hand failure (drift 11.55 -> 7.69 cm,
#        %tracking < 0.5 11.3% -> 5.7%).
#     3. T0-B1 visually fixes the gait failure (both_swing 0.582 ->
#        0.349, LR_corr -0.071 -> -0.306 ~ GT).
#   If the metric story is contradicted on visuals, Tier-1 design
#   pauses and we re-diagnose (Round-26 lesson).
#
# DEFAULT N_CLIPS=16 (per roadmap §9.2: 6 hand-object + 6 walking +
# 4 chair/pelvis ~ 16). Override via env if you want the full 48.
#
# Wall-clock budget (dual-A6000):
#   PAIR (v27 on cuda:0 || T0-A3 on cuda:1)   ~7-9 min
#   SERIAL T0-B1 on cuda:0                     ~3-5 min
#   PACK                                       ~30 s
#   TOTAL                                      ~12-15 min
#
# Prerequisites on the Linux server:
#   1. git pull (must include the Round-27 commits)
#   2. ckpts present at:
#        runs/training/stageB_anchordiff_v27_stage2_anchoraware_FULL_DATA/final.pt
#        runs/training/stageB_anchordiff_t0a3_full_oracle_hint_48clip/final.pt
#        runs/training/stageB_anchordiff_t0b1_temporal_losses_48clip_from_v27/final.pt
#   3. selection JSON at:
#        analyses/round27_tier0_eval_selection_balanced.json
#      (auto-generated by run_round27_t0a_train.sh EVAL stage; if you
#       deleted it after the tarball, re-run that launcher with
#       ROUND27_RESUME_FROM=eval, or pass an override via SEL_JSON= env)
#   4. v27 + T0-A3 + T0-B1 _local.yaml configs:
#        run_round26_make_local_configs.sh  (v27)
#        run_round27_make_local_configs.sh  (t0a3, t0b1)
#
# Usage:
#   bash scripts/stage_b_generator/run_round27_visual_review.sh
#
#   # Render only 8 clips (faster):
#   ROUND27_VIS_N_CLIPS=8 bash scripts/stage_b_generator/run_round27_visual_review.sh
#
#   # Render the full 48-clip Tier-0 subset:
#   ROUND27_VIS_N_CLIPS=48 bash scripts/stage_b_generator/run_round27_visual_review.sh
#
#   # Single-GPU fallback (cuda:0, sequential):
#   ROUND27_VIS_SINGLE_GPU=1 bash scripts/stage_b_generator/run_round27_visual_review.sh
#
set -euo pipefail
cd "$(dirname "$0")/../.."

LOG_DIR="runs/round27_visual_review"
mkdir -p "${LOG_DIR}"

V27_CFG_LOCAL="configs/training/anchordiff_v27_stage2_anchoraware_FULL_DATA_local.yaml"
T0A3_CFG_LOCAL="configs/training/anchordiff_t0a3_full_oracle_hint_48clip_local.yaml"
T0B1_CFG_LOCAL="configs/training/anchordiff_t0b1_temporal_losses_48clip_from_v27_local.yaml"

V27_CKPT="runs/training/stageB_anchordiff_v27_stage2_anchoraware_FULL_DATA/final.pt"
T0A3_CKPT="runs/training/stageB_anchordiff_t0a3_full_oracle_hint_48clip/final.pt"
T0B1_CKPT="runs/training/stageB_anchordiff_t0b1_temporal_losses_48clip_from_v27/final.pt"

SEL_JSON="${SEL_JSON:-analyses/round27_tier0_eval_selection_balanced.json}"
N_CLIPS="${ROUND27_VIS_N_CLIPS:-16}"
SINGLE_GPU="${ROUND27_VIS_SINGLE_GPU:-0}"

OUT_V27="analyses/round27_visual_review/v27_baseline"
OUT_T0A3="analyses/round27_visual_review/t0a3_contact_winner"
OUT_T0B1="analyses/round27_visual_review/t0b1_gait_winner"

# ---------- preflight ----------
for F in "${V27_CFG_LOCAL}" "${T0A3_CFG_LOCAL}" "${T0B1_CFG_LOCAL}" \
         "${V27_CKPT}" "${T0A3_CKPT}" "${T0B1_CKPT}" "${SEL_JSON}"; do
    if [[ ! -e "${F}" ]]; then
        echo "ERROR: missing prerequisite: ${F}"
        if [[ "${F}" == "${V27_CFG_LOCAL}" ]]; then
            echo "  Run: bash scripts/stage_b_generator/run_round26_make_local_configs.sh"
        elif [[ "${F}" == "${T0A3_CFG_LOCAL}" || "${F}" == "${T0B1_CFG_LOCAL}" ]]; then
            echo "  Run: bash scripts/stage_b_generator/run_round27_make_local_configs.sh"
        elif [[ "${F}" == "${SEL_JSON}" ]]; then
            echo "  Run: ROUND27_RESUME_FROM=eval bash scripts/stage_b_generator/run_round27_t0a_train.sh"
        fi
        exit 1
    fi
done

# Render selection size sanity.
SEL_N=$(python -c "import json; print(json.load(open('${SEL_JSON}'))['n_clips'])")
echo "Selection: ${SEL_N} clips available; rendering first ${N_CLIPS}"

mkdir -p "${OUT_V27}" "${OUT_T0A3}" "${OUT_T0B1}"

# Background renderer with logging.
run_step_bg() {
    local NAME="$1"; shift
    local GPU="$1"; shift
    local LOG="${LOG_DIR}/${NAME}.log"
    local T0
    T0=$(date +%s)
    {
        echo "================================================================"
        echo "[$(date '+%F %T')] BG-START ${NAME} on cuda:${GPU}"
        echo "    log: ${LOG}"
        echo "================================================================"
        env CUDA_VISIBLE_DEVICES="${GPU}" \
            PYTHONUNBUFFERED=1 PYTHONIOENCODING=utf-8 "$@" 2>&1
        local T1
        T1=$(date +%s)
        echo "[$(date '+%F %T')] BG-DONE ${NAME} in $((T1-T0))s"
    } > "${LOG}" 2>&1
}

run_step_fg() {
    local NAME="$1"; shift
    local GPU="$1"; shift
    local LOG="${LOG_DIR}/${NAME}.log"
    local T0
    T0=$(date +%s)
    echo
    echo "================================================================"
    echo "[$(date '+%F %T')] START ${NAME} on cuda:${GPU}"
    echo "    log: ${LOG}"
    echo "================================================================"
    env CUDA_VISIBLE_DEVICES="${GPU}" \
        PYTHONUNBUFFERED=1 PYTHONIOENCODING=utf-8 "$@" 2>&1 | tee "${LOG}"
    local T1
    T1=$(date +%s)
    echo "[$(date '+%F %T')] DONE ${NAME} in $((T1-T0))s"
}

# Common renderer args (--bucket train because the 48-clip Tier-0
# subset is in the train bucket).
RENDER_ARGS=(
    --selection-json "${SEL_JSON}"
    --bucket train
    --n-clips "${N_CLIPS}"
    --cfg-scale 1.0
    --seed 42
)

if [[ "${SINGLE_GPU}" == "1" ]]; then
    echo
    echo "================================================================"
    echo "[$(date '+%F %T')] SINGLE-GPU RENDER (cuda:0, sequential 3 ckpts)"
    echo "================================================================"

    run_step_fg "render_v27_baseline" 0 \
        conda run --no-capture-output -n piano python -u \
            scripts/stage_b_generator/render_round24_visual_review.py \
            --config "${V27_CFG_LOCAL}" --ckpt "${V27_CKPT}" \
            --output-dir "${OUT_V27}" "${RENDER_ARGS[@]}"

    run_step_fg "render_t0a3_contact" 0 \
        conda run --no-capture-output -n piano python -u \
            scripts/stage_b_generator/render_round24_visual_review.py \
            --config "${T0A3_CFG_LOCAL}" --ckpt "${T0A3_CKPT}" \
            --output-dir "${OUT_T0A3}" "${RENDER_ARGS[@]}"

    run_step_fg "render_t0b1_gait" 0 \
        conda run --no-capture-output -n piano python -u \
            scripts/stage_b_generator/render_round24_visual_review.py \
            --config "${T0B1_CFG_LOCAL}" --ckpt "${T0B1_CKPT}" \
            --output-dir "${OUT_T0B1}" "${RENDER_ARGS[@]}"
else
    echo
    echo "================================================================"
    echo "[$(date '+%F %T')] DUAL-GPU RENDER: v27 (cuda:0) || T0-A3 (cuda:1)"
    echo "================================================================"

    run_step_bg "render_v27_baseline" 0 \
        conda run --no-capture-output -n piano python -u \
            scripts/stage_b_generator/render_round24_visual_review.py \
            --config "${V27_CFG_LOCAL}" --ckpt "${V27_CKPT}" \
            --output-dir "${OUT_V27}" "${RENDER_ARGS[@]}" &
    PID_V27=$!

    run_step_bg "render_t0a3_contact" 1 \
        conda run --no-capture-output -n piano python -u \
            scripts/stage_b_generator/render_round24_visual_review.py \
            --config "${T0A3_CFG_LOCAL}" --ckpt "${T0A3_CKPT}" \
            --output-dir "${OUT_T0A3}" "${RENDER_ARGS[@]}" &
    PID_T0A3=$!

    echo "    PID v27=${PID_V27}  T0-A3=${PID_T0A3}"
    echo "    follow: tail -f ${LOG_DIR}/render_v27_baseline.log ${LOG_DIR}/render_t0a3_contact.log"

    EX_V27=0; EX_T0A3=0
    wait $PID_V27 || EX_V27=$?
    wait $PID_T0A3 || EX_T0A3=$?
    echo "[$(date '+%F %T')] PAIR DONE (v27=${EX_V27} T0-A3=${EX_T0A3})"

    echo
    echo "================================================================"
    echo "[$(date '+%F %T')] SERIAL: T0-B1 on cuda:0"
    echo "================================================================"
    run_step_fg "render_t0b1_gait" 0 \
        conda run --no-capture-output -n piano python -u \
            scripts/stage_b_generator/render_round24_visual_review.py \
            --config "${T0B1_CFG_LOCAL}" --ckpt "${T0B1_CKPT}" \
            --output-dir "${OUT_T0B1}" "${RENDER_ARGS[@]}"
fi

# ============================================================
# PACK
# ============================================================
echo
echo "================================================================"
echo "[$(date '+%F %T')] PACK results"
echo "================================================================"
bash scripts/stage_b_generator/round27_visual_review_pack.sh

echo
echo "================================================================"
echo "Round-27 visual review complete."
echo "Outputs:"
echo "  v27 baseline videos:   ${OUT_V27}/clip*_{gt,pred}.mp4  + summary.md"
echo "  T0-A3 contact videos:  ${OUT_T0A3}/clip*_{gt,pred}.mp4 + summary.md"
echo "  T0-B1 gait videos:     ${OUT_T0B1}/clip*_{gt,pred}.mp4 + summary.md"
echo "  Selection JSON:        ${SEL_JSON}"
echo "  Stage logs:            ${LOG_DIR}/*.log"
echo "  Tarball:               round27_visual_review_*.tar.gz at project root"
echo "================================================================"
